### PR TITLE
Update to use latest Packer Plugin SDK v0.0.13

### PR DESCRIPTION
**Pull request by nywilken**
Hi! I'm a maintainer over at Packer and I wanted to make this PR to make your life a tad easier -- we'll be releasing v1.7.0 tomorrow and it will include a backwards-breaking API change. This PR should be all you need to get yourself upgraded to work with v1.7.

That said, there's a little more legwork for you to do if you want your plugin to be compatible with the packer init feature we'll also be implementing in that release. We have an upgrade guide here: https://github.com/hashicorp/packer/blob/master/website/content/guides/1.7-plugin-upgrade.mdx

Let me know if you have any issues. I couldn't actually test the builder against Vultr as I don't have an environment for it. But I was able to load and validate a sample configuration with the updated plugin.

<details>
<summary> Debug log </summary>

```
~>  PACKER_LOG=1 packer.test build sample.json
2021/02/16 20:50:44 [INFO] Packer version: 1.7.0-dev [go1.15.2 linux amd64]
2021/02/16 20:50:44 [TRACE] discovering plugins in /home/wilken/bin
2021/02/16 20:50:44 [TRACE] discovering plugins in /home/wilken/.packer.d/plugins
2021/02/16 20:50:44 [DEBUG] Discovered plugin: vultr = /home/wilken/.packer.d/plugins/packer-builder-vultr
2021/02/16 20:50:44 [INFO] using external builders: [vultr]
2021/02/16 20:50:44 [DEBUG] Discovered plugin: comment = /home/wilken/.packer.d/plugins/packer-provisioner-comment
2021/02/16 20:50:44 using external provisioners [comment]
2021/02/16 20:50:44 [DEBUG] Discovered plugin: compress = /home/wilken/.packer.d/plugins/packer-plugin-compress
2021/02/16 20:50:44 [DEBUG] Discovered plugin: docker = /home/wilken/.packer.d/plugins/packer-plugin-docker
2021/02/16 20:50:44 [INFO] found external [-packer-default-plugin-name-] post-processors from compress plugin
2021/02/16 20:50:44 [INFO] found external [-packer-default-plugin-name-] builders from docker plugin
2021/02/16 20:50:44 [INFO] found external [import push save tag] post-processors from docker plugin
2021/02/16 20:50:44 [TRACE] discovering plugins in .
2021/02/16 20:50:44 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/02/16 20:50:44 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/wilken/.packerconfig
2021/02/16 20:50:44 [WARN] Config file doesn't exist: /home/wilken/.packerconfig
2021/02/16 20:50:44 [INFO] Setting cache directory: /home/wilken/Development/packer-builder-vultr/packer_cache
2021/02/16 20:50:44 [TRACE] Starting external plugin /home/wilken/.packer.d/plugins/packer-builder-vultr
2021/02/16 20:50:44 Starting plugin: /home/wilken/.packer.d/plugins/packer-builder-vultr []string{"/home/wilken/.packer.d/plugins/packer-builder-vultr"}
2021/02/16 20:50:44 Waiting for RPC address for: /home/wilken/.packer.d/plugins/packer-builder-vultr
2021/02/16 20:50:44 Received unix RPC address for /home/wilken/.packer.d/plugins/packer-builder-vultr: addr is /tmp/packer-plugin507313424
2021/02/16 20:50:44 packer-builder-vultr plugin: 2021/02/16 20:50:44 Plugin address: unix /tmp/packer-plugin507313424
2021/02/16 20:50:44 packer-builder-vultr plugin: 2021/02/16 20:50:44 Waiting for connection...
2021/02/16 20:50:44 packer-builder-vultr plugin: 2021/02/16 20:50:44 Serving a plugin connection...
2021/02/16 20:50:44 Preparing build: vultr
2021/02/16 20:50:44 Build debug mode: false
2021/02/16 20:50:44 Force build: false
2021/02/16 20:50:44 On error:
2021/02/16 20:50:44 Waiting on builds to complete...
vultr: output will be in this color.

2021/02/16 20:50:44 Starting build run: vultr
2021/02/16 20:50:44 Running builder: vultr
2021/02/16 20:50:44 [INFO] (telemetry) Starting builder vultr
==> vultr: Running Vultr builder...
==> vultr: Creating temporary SSH key...
2021/02/16 20:50:45 [INFO] (telemetry) ending vultr
==> vultr: Error creating temporary SSH key: {"error":"Unauthorized.","status":401}
==> Wait completed after 925 milliseconds 424 microseconds
2021/02/16 20:50:45 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2021/02/16 20:50:45 machine readable: vultr,error []string{"Error creating temporary SSH key: {\"error\":\"Unauthorized.\",\"status\":401}"}
==> Builds finished but no artifacts were created.
2021/02/16 20:50:45 [INFO] (telemetry) Finalizing.
Build 'vultr' errored after 925 milliseconds 245 microseconds: Error creating temporary SSH key: {"error":"Unauthorized.","status":401}

==> Wait completed after 925 milliseconds 424 microseconds

==> Some builds didn't complete successfully and had errors:
--> vultr: Error creating temporary SSH key: {"error":"Unauthorized.","status":401}

==> Builds finished but no artifacts were created.
2021/02/16 20:50:45 waiting for all plugin processes to complete...
2021/02/16 20:50:45 /home/wilken/.packer.d/plugins/packer-builder-vultr: plugin process exited
```
</details>

### CODE REVIEW

**Comment by ddymko** [comment]
@nywilken Thanks a whole bunch for the PR! 

I don't mind pulling down the changes and testing it out. If the packer team would want a test environment for Vultr let me know.

**Comment by ddymko** [comment]
Pulled down the changes and ran the Acceptance test (and unit) - no issues
<details>
<summary> log </summary>
```
GOROOT=/usr/local/Cellar/go/1.15.8/libexec #gosetup
GOPATH=/Users/ddymko/go #gosetup
/usr/local/Cellar/go/1.15.8/libexec/bin/go test -json ./...
=== RUN   TestArtifact_Impl
--- PASS: TestArtifact_Impl (0.00s)
=== RUN   TestArtifactId
--- PASS: TestArtifactId (0.00s)
=== RUN   TestArtifactString
--- PASS: TestArtifactString (0.00s)
=== RUN   TestBuilderAcc_basic
2021/02/16 21:40:19 [DEBUG] Parsing template...
2021/02/16 21:40:19 [DEBUG] Initializing core...
2021/02/16 21:40:19 [DEBUG] Retrieving 'test' build
2021/02/16 21:40:19 [DEBUG] Preparing 'test' build
2021/02/16 21:40:19 [DEBUG] Running 'test' build
2021/02/16 21:40:19 Running builder: test
2021/02/16 21:40:19 ui: ==> test: Running Vultr builder...
2021/02/16 21:40:19 ui: ==> test: Creating temporary SSH key...
2021/02/16 21:40:19 ui: ==> test: Creating Vultr instance...
2021/02/16 21:40:20 ui: ==> test: Waiting 1200s for server 519709ff-869b-4724-beb3-0bfe5a0634ce to power on...
2021/02/16 21:40:20 Waiting for up to 1200 seconds for server
2021/02/16 21:40:20 Checking server status... (attempt: 1)
2021/02/16 21:40:23 Checking server status... (attempt: 2)
2021/02/16 21:40:26 Checking server status... (attempt: 3)
2021/02/16 21:40:29 Checking server status... (attempt: 4)
2021/02/16 21:40:32 Checking server status... (attempt: 5)
2021/02/16 21:40:35 Checking server status... (attempt: 6)
2021/02/16 21:40:39 Checking server status... (attempt: 7)
2021/02/16 21:40:39 ui: ==> test: Using ssh communicator to connect: 45.77.98.233
2021/02/16 21:40:39 [INFO] Waiting for SSH, up to timeout: 5m0s
2021/02/16 21:40:39 ui: ==> test: Waiting for SSH to become available...
2021/02/16 21:40:54 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 45.77.98.233:22: i/o timeout
2021/02/16 21:41:14 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 45.77.98.233:22: i/o timeout
2021/02/16 21:41:34 [DEBUG] TCP connection to SSH ip/port failed: dial tcp 45.77.98.233:22: i/o timeout
2021/02/16 21:41:39 [INFO] Attempting SSH connection to 45.77.98.233:22...
2021/02/16 21:41:39 [DEBUG] reconnecting to TCP connection for SSH
2021/02/16 21:41:39 [DEBUG] handshaking with SSH
2021/02/16 21:41:39 [DEBUG] handshake complete!
2021/02/16 21:41:39 [DEBUG] Opening new ssh session
2021/02/16 21:41:39 [INFO] agent forwarding enabled
2021/02/16 21:41:39 ui: ==> test: Connected to SSH!
2021/02/16 21:41:39 Running the provision hook
2021/02/16 21:41:39 ui: ==> test: Performing graceful shutdown...
2021/02/16 21:41:49 [DEBUG] Opening new ssh session
2021/02/16 21:41:49 [DEBUG] starting remote command: shutdown -P now
2021/02/16 21:41:49 [ERROR] Remote command exited without exit status or exit signal.
2021/02/16 21:41:49 ui: ==> test: Server successfully shutdown
2021/02/16 21:41:59 ui: ==> test: Waiting 1200s for snapshot fc210dad-e715-4288-ba30-831b24e2c5c9 to complete...
2021/02/16 21:41:59 Waiting for up to 1200 seconds for snapshot
2021/02/16 21:41:59 Checking snapshot status... (attempt: 1)
2021/02/16 21:42:03 Checking snapshot status... (attempt: 2)
2021/02/16 21:42:06 Checking snapshot status... (attempt: 3)
2021/02/16 21:42:09 Checking snapshot status... (attempt: 4)
2021/02/16 21:42:12 Checking snapshot status... (attempt: 5)
2021/02/16 21:42:15 Checking snapshot status... (attempt: 6)
2021/02/16 21:42:18 Checking snapshot status... (attempt: 7)
2021/02/16 21:42:21 Checking snapshot status... (attempt: 8)
2021/02/16 21:42:25 Checking snapshot status... (attempt: 9)
2021/02/16 21:42:28 Checking snapshot status... (attempt: 10)
2021/02/16 21:42:31 Checking snapshot status... (attempt: 11)
2021/02/16 21:42:34 Checking snapshot status... (attempt: 12)
2021/02/16 21:42:37 Checking snapshot status... (attempt: 13)
2021/02/16 21:42:40 Checking snapshot status... (attempt: 14)
2021/02/16 21:42:44 Checking snapshot status... (attempt: 15)
2021/02/16 21:42:47 Checking snapshot status... (attempt: 16)
2021/02/16 21:42:50 Checking snapshot status... (attempt: 17)
2021/02/16 21:42:53 Checking snapshot status... (attempt: 18)
2021/02/16 21:42:56 Checking snapshot status... (attempt: 19)
2021/02/16 21:42:59 Checking snapshot status... (attempt: 20)
2021/02/16 21:43:02 Checking snapshot status... (attempt: 21)
2021/02/16 21:43:06 Checking snapshot status... (attempt: 22)
2021/02/16 21:43:09 Checking snapshot status... (attempt: 23)
2021/02/16 21:43:12 Checking snapshot status... (attempt: 24)
2021/02/16 21:43:15 Checking snapshot status... (attempt: 25)
2021/02/16 21:43:18 Checking snapshot status... (attempt: 26)
2021/02/16 21:43:21 Checking snapshot status... (attempt: 27)
2021/02/16 21:43:25 Checking snapshot status... (attempt: 28)
2021/02/16 21:43:28 Checking snapshot status... (attempt: 29)
2021/02/16 21:43:31 Checking snapshot status... (attempt: 30)
2021/02/16 21:43:34 Checking snapshot status... (attempt: 31)
2021/02/16 21:43:37 Checking snapshot status... (attempt: 32)
2021/02/16 21:43:40 Checking snapshot status... (attempt: 33)
2021/02/16 21:43:44 Checking snapshot status... (attempt: 34)
2021/02/16 21:43:47 Checking snapshot status... (attempt: 35)
2021/02/16 21:43:50 Checking snapshot status... (attempt: 36)
2021/02/16 21:43:53 Checking snapshot status... (attempt: 37)
2021/02/16 21:43:56 Checking snapshot status... (attempt: 38)
2021/02/16 21:43:59 Checking snapshot status... (attempt: 39)
2021/02/16 21:44:03 Checking snapshot status... (attempt: 40)
2021/02/16 21:44:06 Checking snapshot status... (attempt: 41)
2021/02/16 21:44:09 Checking snapshot status... (attempt: 42)
2021/02/16 21:44:12 Checking snapshot status... (attempt: 43)
2021/02/16 21:44:15 Checking snapshot status... (attempt: 44)
2021/02/16 21:44:18 Checking snapshot status... (attempt: 45)
2021/02/16 21:44:21 Checking snapshot status... (attempt: 46)
2021/02/16 21:44:25 Checking snapshot status... (attempt: 47)
2021/02/16 21:44:28 Checking snapshot status... (attempt: 48)
2021/02/16 21:44:31 Checking snapshot status... (attempt: 49)
2021/02/16 21:44:34 Checking snapshot status... (attempt: 50)
2021/02/16 21:44:37 Checking snapshot status... (attempt: 51)
2021/02/16 21:44:41 Checking snapshot status... (attempt: 52)
2021/02/16 21:44:44 Checking snapshot status... (attempt: 53)
2021/02/16 21:44:47 Checking snapshot status... (attempt: 54)
2021/02/16 21:44:50 Checking snapshot status... (attempt: 55)
2021/02/16 21:44:53 Checking snapshot status... (attempt: 56)
2021/02/16 21:44:56 Checking snapshot status... (attempt: 57)
2021/02/16 21:44:59 Checking snapshot status... (attempt: 58)
2021/02/16 21:45:03 Checking snapshot status... (attempt: 59)
2021/02/16 21:45:06 Checking snapshot status... (attempt: 60)
2021/02/16 21:45:09 Checking snapshot status... (attempt: 61)
2021/02/16 21:45:12 Checking snapshot status... (attempt: 62)
2021/02/16 21:45:15 Checking snapshot status... (attempt: 63)
2021/02/16 21:45:18 Checking snapshot status... (attempt: 64)
2021/02/16 21:45:22 Checking snapshot status... (attempt: 65)
2021/02/16 21:45:25 Checking snapshot status... (attempt: 66)
2021/02/16 21:45:28 Checking snapshot status... (attempt: 67)
2021/02/16 21:45:31 Checking snapshot status... (attempt: 68)
2021/02/16 21:45:34 Checking snapshot status... (attempt: 69)
2021/02/16 21:45:37 Checking snapshot status... (attempt: 70)
2021/02/16 21:45:41 Checking snapshot status... (attempt: 71)
2021/02/16 21:45:44 Checking snapshot status... (attempt: 72)
2021/02/16 21:45:47 Checking snapshot status... (attempt: 73)
2021/02/16 21:45:50 Checking snapshot status... (attempt: 74)
2021/02/16 21:45:53 Checking snapshot status... (attempt: 75)
2021/02/16 21:45:56 Checking snapshot status... (attempt: 76)
2021/02/16 21:46:00 Checking snapshot status... (attempt: 77)
2021/02/16 21:46:03 Checking snapshot status... (attempt: 78)
2021/02/16 21:46:06 Checking snapshot status... (attempt: 79)
2021/02/16 21:46:09 Checking snapshot status... (attempt: 80)
2021/02/16 21:46:12 Checking snapshot status... (attempt: 81)
2021/02/16 21:46:15 Checking snapshot status... (attempt: 82)
2021/02/16 21:46:18 Checking snapshot status... (attempt: 83)
2021/02/16 21:46:22 Checking snapshot status... (attempt: 84)
2021/02/16 21:46:25 Checking snapshot status... (attempt: 85)
2021/02/16 21:46:28 Checking snapshot status... (attempt: 86)
2021/02/16 21:46:31 Checking snapshot status... (attempt: 87)
2021/02/16 21:46:34 Checking snapshot status... (attempt: 88)
2021/02/16 21:46:37 Checking snapshot status... (attempt: 89)
2021/02/16 21:46:41 Checking snapshot status... (attempt: 90)
2021/02/16 21:46:44 Checking snapshot status... (attempt: 91)
2021/02/16 21:46:47 Checking snapshot status... (attempt: 92)
2021/02/16 21:46:50 Checking snapshot status... (attempt: 93)
2021/02/16 21:46:53 Checking snapshot status... (attempt: 94)
2021/02/16 21:46:56 Checking snapshot status... (attempt: 95)
2021/02/16 21:46:59 Checking snapshot status... (attempt: 96)
2021/02/16 21:47:03 Checking snapshot status... (attempt: 97)
2021/02/16 21:47:06 Checking snapshot status... (attempt: 98)
2021/02/16 21:47:09 Checking snapshot status... (attempt: 99)
2021/02/16 21:47:12 Checking snapshot status... (attempt: 100)
2021/02/16 21:47:15 Checking snapshot status... (attempt: 101)
2021/02/16 21:47:18 Checking snapshot status... (attempt: 102)
2021/02/16 21:47:21 Checking snapshot status... (attempt: 103)
2021/02/16 21:47:24 Checking snapshot status... (attempt: 104)
2021/02/16 21:47:28 Checking snapshot status... (attempt: 105)
2021/02/16 21:47:31 Checking snapshot status... (attempt: 106)
2021/02/16 21:47:34 Checking snapshot status... (attempt: 107)
2021/02/16 21:47:37 Checking snapshot status... (attempt: 108)
2021/02/16 21:47:40 Checking snapshot status... (attempt: 109)
2021/02/16 21:47:44 Checking snapshot status... (attempt: 110)
2021/02/16 21:47:47 Checking snapshot status... (attempt: 111)
2021/02/16 21:47:50 Checking snapshot status... (attempt: 112)
2021/02/16 21:47:53 Checking snapshot status... (attempt: 113)
2021/02/16 21:47:56 Checking snapshot status... (attempt: 114)
2021/02/16 21:47:59 Checking snapshot status... (attempt: 115)
2021/02/16 21:48:02 Checking snapshot status... (attempt: 116)
2021/02/16 21:48:06 Checking snapshot status... (attempt: 117)
2021/02/16 21:48:09 Checking snapshot status... (attempt: 118)
2021/02/16 21:48:12 Checking snapshot status... (attempt: 119)
2021/02/16 21:48:15 Checking snapshot status... (attempt: 120)
2021/02/16 21:48:18 Checking snapshot status... (attempt: 121)
2021/02/16 21:48:21 Checking snapshot status... (attempt: 122)
2021/02/16 21:48:24 Checking snapshot status... (attempt: 123)
2021/02/16 21:48:28 Checking snapshot status... (attempt: 124)
2021/02/16 21:48:28 ui: ==> test: Destroying server 519709ff-869b-4724-beb3-0bfe5a0634ce
2021/02/16 21:48:28 ui: ==> test: Deleting temporary SSH key...
2021/02/16 21:48:28 Destroying Vultr Snapshot: fc210dad-e715-4288-ba30-831b24e2c5c9 (packer-test-snapshot)
--- PASS: TestBuilderAcc_basic (489.92s)
=== RUN   TestBuilder_ImplementsBuilder
--- PASS: TestBuilder_ImplementsBuilder (0.00s)
=== RUN   TestBuilder_Prepare_BadType
--- PASS: TestBuilder_Prepare_BadType (0.00s)
=== RUN   TestBuilderPrepare_InvalidKey
--- PASS: TestBuilderPrepare_InvalidKey (0.00s)
=== RUN   TestBuilderPrepare_RegionID
--- PASS: TestBuilderPrepare_RegionID (0.00s)
=== RUN   TestBuilderPrepare_OSID
--- PASS: TestBuilderPrepare_OSID (0.00s)
=== RUN   TestBuilderPrepare_PlanID
--- PASS: TestBuilderPrepare_PlanID (0.00s)
=== RUN   TestBuilderPrepare_Description
--- PASS: TestBuilderPrepare_Description (0.00s)
=== RUN   TestBuilderPrepare_StateTimeout
--- PASS: TestBuilderPrepare_StateTimeout (0.00s)
=== RUN   TestBuilderPrepare_EnablePrivateNetwork
--- PASS: TestBuilderPrepare_EnablePrivateNetwork (0.00s)
=== RUN   TestBuilderPrepare_EnableIPV6
--- PASS: TestBuilderPrepare_EnableIPV6 (0.00s)
=== RUN   TestBuilderPrepare_Label
--- PASS: TestBuilderPrepare_Label (0.00s)
PASS
ok  	github.com/vultr/packer-builder-vultr/vultr	490.179s

Process finished with exit code 0
```
<details>

**Review by ddymko — APPROVED** [review]
Tested the single binary build against 1.7.0 and it runs fine. Will setup another PR to change support `packer init`

**Review by Oogy — APPROVED** [review]

**Comment by nywilken** [comment]
> Tested the single binary build against 1.7.0 and it runs fine. Will setup another PR to change support `packer init`

Hi @ddymko, @Oogy 

Thanks for testing and merging the PR. Happy that we were able to get in a change for v1.7.0, which is officially out. The latest documentation on Packer init and the migration guides are on Packer.io. 

https://www.packer.io/docs/plugins
https://www.packer.io/guides/1.7-plugin-upgrade 
https://www.packer.io/guides/1.7-template-upgrade

Please feel free to reach out if you have any questions or run into any issues with supporting `packer init`.

**Pull request merged**
